### ISSUE TITLE
Failure to insert error

### ISSUE THREAD

**Issue by mgwidmann** [mgwidmann/flames#2]
Got the following error on my production app (in the log file, not in flames)

```
20:53:24.808 [error] ** (FunctionClauseError) no function clause matching in String.Break.trim_leading/1
    (elixir) unicode/unicode.ex:375: String.Break.trim_leading(["\n    " | ":pubkey_pbe.decode(DATA_OMITTED)
    (elixir) lib/string.ex:833: String.trim/1
    (flames) lib/flames/logger.ex:102: Flames.Logger.normalize_message/1
    (flames) lib/flames/logger.ex:66: Flames.Logger.error_changeset/2
    (flames) lib/flames/logger.ex:41: Flames.Logger.post_event/2
    (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```

**Comment by mgwidmann** [comment]
Another example of failed insert:

```
 ** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
     (elixir) lib/io.ex:445: IO.chardata_to_string(32)
     (flames) lib/flames/logger.ex:101: Flames.Logger.normalize_message/1
     (flames) lib/flames/logger.ex:66: Flames.Logger.error_changeset/2
     (flames) lib/flames/logger.ex:41: Flames.Logger.post_event/2
     (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
```
